export const CANDIDAT_ADDED_REQUEST = "CANDIDAT_ADDED_REQUEST";
export const CANDIDAT_ADDED_SUCCESS = "CANDIDAT_ADDED_SUCCESS";
export const CANDIDAT_ADDED_FAIL = "CANDIDAT_ADDED_FAIL";
export const CANDIDAT_ADDED_RESET = "JOB_UPDATED_RESET";

export const ALL_CANDIDATS_LOAD_REQUEST = "ALL_CANDIDATS_LOAD_REQUEST";
export const ALL_CANDIDATS_LOAD_SUCCESS = "ALL_CANDIDATS_LOAD_SUCCESS";
export const ALL_CANDIDATS_LOAD_FAIL = "ALL_CANDIDATS_LOAD_FAIL";
export const ALL_CANDIDATS_LOAD_RESET = "ALL_CANDIDATS_LOAD_RESET";


export const CANDIDAT_DELETED_REQUEST = "CANDIDAT_DELETED_REQUEST";
export const CANDIDAT_DELETED_SUCCESS = "CANDIDAT_DELETED_SUCCESS";
export const CANDIDAT_DELETED_FAIL = "CANDIDAT_DELETED_FAIL";
export const CANDIDAT_DELETED_RESET = "CANDIDAT_DELETED_RESET";



export const CANDIDAT_LOAD_SINGLE_REQUEST = "CANDIDAT_LOAD_SINGLE_REQUEST";
export const CANDIDAT_LOAD_SINGLE_SUCCESS = "CANDIDAT_LOAD_SINGLE_SUCCESS";
export const CANDIDAT_LOAD_SINGLE_FAIL = "CANDIDAT_LOAD_SINGLE_FAIL";
export const CANDIDAT_LOAD_SINGLE_RESET = "CANDIDAT_LOAD_SINGLE_RESET";


export const CANDIDAT_UPDATED_REQUEST = "CANDIDAT_UPDATED_REQUEST";
export const CANDIDAT_UPDATED_SUCCESS = "CANDIDAT_UPDATED_SUCCESS";
export const CANDIDAT_UPDATED_FAIL = "CANDIDAT_UPDATED_FAIL";
export const CANDIDAT_UPDATED_RESET = "CANDIDAT_UPDATED_RESET";

export const ALL_RECRUITER_CANDIDATS_LOAD_REQUEST = "ALL_RECRUITER_CANDIDATS_LOAD_REQUEST";
export const ALL_RECRUITER_CANDIDATS_LOAD_SUCCESS = "ALL_RECRUITER_CANDIDATS_LOAD_SUCCESS";
export const ALL_RECRUITER_CANDIDATS_LOAD_FAIL = "ALL_RECRUITER_CANDIDATS_LOAD_FAIL";
export const ALL_RECRUITER_CANDIDATS_LOAD_RESET = "ALL_RECRUITER_CANDIDATS_LOAD_RESET";

export const ALL_JOBSEEKER_CANDIDATS_LOAD_REQUEST = "ALL_JOBSEEKER_CANDIDATS_LOAD_REQUEST";
export const ALL_JOBSEEKER_CANDIDATS_LOAD_SUCCESS = "ALL_JOBSEEKER_CANDIDATS_LOAD_SUCCESS";
export const ALL_JOBSEEKER_CANDIDATS_LOAD_FAIL = "ALL_JOBSEEKER_CANDIDATS_LOAD_FAIL";
export const ALL_JOBSEEKER_CANDIDATS_LOAD_RESET = "ALL_JOBSEEKER_CANDIDATS_LOAD_RESET";
