export const FORM_LOAD_SINGLE_REQUEST = "FORM_LOAD_SINGLE_REQUEST";
export const FORM_LOAD_SINGLE_SUCCESS = "FORM_LOAD_SINGLE_SUCCESS";
export const FORM_LOAD_SINGLE_FAIL = "FORM_LOAD_SINGLE_FAIL";
export const FORM_LOAD_SINGLE_RESET = "FORM_LOAD_SINGLE_RESET";


export const FORM_LOAD_ALL_REQUEST = "FORM_LOAD_ALL_REQUEST";
export const FORM_LOAD_ALL_SUCCESS = "FORM_LOAD_ALL_SUCCESS";
export const FORM_LOAD_ALL_FAIL = "FORM_LOAD_ALL_FAIL";
export const FORM_LOAD_ALL_RESET = "FORM_LOAD_ALL_RESET";

export const FORM_DELETED_REQUEST = "FORM_DELETED_REQUEST";
export const FORM_DELETED_SUCCESS = "FORM_DELETED_SUCCESS";
export const FORM_DELETED_FAIL = "FORM_DELETED_FAIL";
export const FORM_DELETED_RESET = "FORM_DELETED_RESET";



