export const JOB_LOAD_REQUEST = "JOB_LOAD_REQUEST";
export const JOB_LOAD_SUCCESS = "JOB_LOAD_SUCCESS";
export const JOB_LOAD_FAIL = "JOB_LOAD_FAIL";
export const JOB_LOAD_RESET = "JOB_LOAD_RESET";



export const JOB_LOAD_SINGLE_REQUEST = "JOB_LOAD_SINGLE_REQUEST";
export const JOB_LOAD_SINGLE_SUCCESS = "JOB_LOAD_SINGLE_SUCCESS";
export const JOB_LOAD_SINGLE_FAIL = "JOB_LOAD_SINGLE_FAIL";
export const JOB_LOAD_SINGLE_RESET = "JOB_LOAD_SINGLE_RESET";


export const JOB_LOAD_ALL_REQUEST = "JOB_LOAD_ALL_REQUEST";
export const JOB_LOAD_ALL_SUCCESS = "JOB_LOAD_ALL_SUCCESS";
export const JOB_LOAD_ALL_FAIL = "JOB_LOAD_ALL_FAIL";
export const JOB_LOAD_ALL_RESET = "JOB_LOAD_ALL_RESET";


export const JOB_VERIFIED_REQUEST = "JOB_VERIFIED_REQUEST";
export const JOB_VERIFIED_SUCCESS = "JOB_VERIFIED_SUCCESS";
export const JOB_VERIFIED_FAIL = "JOB_VERIFIED_FAIL";
export const JOB_VERIFIED_RESET = "JOB_VERIFIED_RESET";

export const JOB_DELETED_REQUEST = "JOB_DELETED_REQUEST";
export const JOB_DELETED_SUCCESS = "JOB_DELETED_SUCCESS";
export const JOB_DELETED_FAIL = "JOB_DELETED_FAIL";
export const JOB_DELETED_RESET = "JOB_DELETED_RESET";


export const JOB_CREATED_REQUEST = "JOB_CREATED_REQUEST";
export const JOB_CREATED_SUCCESS = "JOB_CREATED_SUCCESS";
export const JOB_CREATED_FAIL = "JOB_CREATED_FAIL";
export const JOB_CREATED_RESET = "JOB_CREATED_RESET";

export const JOB_UPDATED_REQUEST = "JOB_UPDATED_REQUEST";
export const JOB_UPDATED_SUCCESS = "JOB_UPDATED_SUCCESS";
export const JOB_UPDATED_FAIL = "JOB_UPDATED_FAIL";
export const JOB_UPDATED_RESET = "JOB_UPDATED_RESET";