export const USER_JOB_REQUEST = "USER_JOB_REQUEST";
export const USER_JOB_SUCCESS = "USER_JOB_SUCCESS";
export const USER_JOB_FAIL = "USER_JOB_FAIL";
export const USER_JOB_RESET = "USER_JOB_RESET";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
export const USER_PROFILE_RESET = "USER_PROFILE_RESET";