export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNIN_RESET = "USER_SIGNIN_RESET";


export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";
export const USER_LOGOUT_RESET = "USER_LOGOUT_RESET";




export const ALL_USER_LOAD_REQUEST = "ALL_USER_LOAD_REQUEST";
export const ALL_USER_LOAD_SUCCESS = "ALL_USER_LOAD_SUCCESS";
export const ALL_USER_LOAD_FAIL = "ALL_USER_LOAD_FAIL";
export const ALL_USER_LOAD_RESET = "ALL_USER_LOAD_RESET";


export const USER_LOAD_SINGLE_REQUEST = "USER_LOAD_SINGLE_REQUEST";
export const USER_LOAD_SINGLE_SUCCESS = "USER_LOAD_SINGLE_SUCCESS";
export const USER_LOAD_SINGLE_FAIL = "USER_LOAD_SINGLE_FAIL";
export const USER_LOAD_SINGLE_RESET = "USER_LOAD_SINGLE_RESET";

export const USER_LOAD_PDF_SINGLE_REQUEST = "USER_LOAD_PDF_SINGLE_REQUEST";
export const USER_LOAD_PDF_SINGLE_SUCCESS = "USER_LOAD_PDF_SINGLE_SUCCESS";
export const USER_LOAD_PDF_SINGLE_FAIL = "USER_LOAD_PDF_SINGLE_FAIL";
export const USER_LOAD_PDF_SINGLE_RESET = "USER_LOAD_PDF_SINGLE_RESET";


export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAIL = "USER_SIGNUP_FAIL";
export const USER_SIGNUP_RESET = "USER_SIGNUP_RESET";

export const USER_DELETED_REQUEST = "USER_DELETED_REQUEST";
export const USER_DELETED_SUCCESS = "USER_DELETED_SUCCESS";
export const USER_DELETED_FAIL = "USER_DELETED_FAIL";
export const USER_DELETED_RESET = "USER_DELETED_RESET";

export const USER_ADDED_REQUEST = "USER_ADDED_REQUEST";
export const USER_ADDED_SUCCESS = "USER_ADDED_SUCCESS";
export const USER_ADDED_FAIL = "USER_ADDED_FAIL";
export const USER_ADDED_RESET = "USER_ADDED_RESET";

export const USER_UPDATED_REQUEST = "USER_UPDATED_REQUEST";
export const USER_UPDATED_SUCCESS = "USER_UPDATED_SUCCESS";
export const USER_UPDATED_FAIL = "USER_UPDATED_FAIL";
export const USER_UPDATED_RESET = "USER_UPDATED_RESET";

export const EMAIL_CHECKED_REQUEST = "EMAIL_CHECKED_REQUEST";
export const EMAIL_CHECKED_SUCCESS = "EMAIL_CHECKED_SUCCESS";
export const EMAIL_CHECKED_FAIL = "EMAIL_CHECKED_FAIL";
export const EMAIL_CHECKED_RESET = "EMAIL_CHECKED_RESET";


